############## Comment these property if you need to load the file on start up ##
#app.vector.load-on-start-up=true
#app.vector.pdf.file-path=C:\\Works\\ebooks\\16_EBOOK-7th_ed_software_engineering_a_practitioners_approach_by_roger_s._pressman_.pdf

################################
#
#
spring.application.name=simple-spring-ai-rag=example


logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=DEBUG



# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb?options=-c%20TimeZone=Asia/Kolkata

spring.datasource.username=soham
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring AI OpenAI Configuration
spring.ai.openai.base-url=http://localhost:1234
spring.ai.openai.api-key=""
spring.ai.openai.embedding.options.model=text-embedding-nomic-embed-text-v1.5
spring.ai.openai.chat.options.model=ai/gemma3
spring.ai.openai.chat.base-url=http://localhost:12434/engines
spring.ai.openai.chat.api-key=ignored

# Spring AI Vector Configuration
#spring.ai.vectorstore.pgvector.index-type=HNSW
#spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
#spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.max-document-batch-size=10000
#spring.ai.vectorstore.pgvector.schema-validation=true
#spring.ai.vectorstore.pgvector.table-name=vector_store_pdf