############## Comment these property if you need to load the file on start up ##
app.vector.load-on-start-up=true
app.vector.pdf.file-path=C:\\Works\\ebooks\\literature\\Ideal Science and Research Welfare Hub.pdf
# Home and About Section
iee.website.app.department-website-links.Home|?=https://iiekalyani.com/About
iee.website.app.department-website-links.About|Institute Overview=https://iiekalyani.com/aboutus/
iee.website.app.department-website-links.About|Chairman?s Message=https://iiekalyani.com/chairman-message/
iee.website.app.department-website-links.About|Principal?s Message=https://iiekalyani.com/principal-message/
iee.website.app.department-website-links.About|Secretary?s Message=https://iiekalyani.com/secretary-message/

# Admission Section
iee.website.app.department-website-links.Admission|Overview=https://iiekalyani.com/admission
iee.website.app.department-website-links.Admission|Eligibility Criteria=https://iiekalyani.com/admission/eligibility
iee.website.app.department-website-links.Admission|Fee Structure=https://iiekalyani.com/admission/fee-structure
iee.website.app.department-website-links.Admission|How to Apply=https://iiekalyani.com/admission/how-to-apply
iee.website.app.department-website-links.Admission|WBJEE Guidelines=https://iiekalyani.com/admission/wbjee-guidelines
iee.website.app.department-website-links.Admission|JEE Main Guidelines=https://iiekalyani.com/admission/jee-guidelines
iee.website.app.department-website-links.Admission|Scholarship / Financial Aid=https://iiekalyani.com/admission/scholarship
iee.website.app.department-website-links.Admission|Notices / Updates=https://iiekalyani.com/admission/notices

# Other Main Menus
iee.website.app.department-website-links.Academic|?=https://iiekalyani.com/academic
iee.website.app.department-website-links.Training & Placement|?=https://iiekalyani.com/training-placement
iee.website.app.department-website-links.Campus Life|?=https://iiekalyani.com/campus-life
iee.website.app.department-website-links.Download|?=https://iiekalyani.com/download
iee.website.app.department-website-links.Student Section|?=https://iiekalyani.com/student-section
iee.website.app.department-website-links.Career|?=https://iiekalyani.com/career
iee.website.app.department-website-links.Contact|?=https://iiekalyani.com/contact
iee.website.app.department-website-links.E Brochure|?=https://iiekalyani.com/e-brochure
iee.website.app.department-website-links.Admission Helpline|?=tel:+91-7449522271

# Departments
iee.website.app.department-website-links.ai =https://iiekalyani.com/department/artificial-intelligence-machine-learning
iee.website.app.department-website-links.cse=https://iiekalyani.com/department/computer-science-engineering
iee.website.app.department-website-links.ece=https://iiekalyani.com/department/electronics-communication-engineering
iee.website.app.department-website-links.ce=https://iiekalyani.com/department/civil-engineering
iee.website.app.department-website-links.me=https://iiekalyani.com/department/mechanical-engineering
iee.website.app.department-website-links.ee=https://iiekalyani.com/department/electrical-engineering
iee.website.app.department-website-links.bba=https://iiekalyani.com/department/bba
################################
#
#
spring.application.name=simple-spring-ai-rag=example


logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=DEBUG



# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb?options=-c%20TimeZone=Asia/Kolkata

spring.datasource.username=soham
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring AI OpenAI Configuration
spring.ai.openai.base-url=http://localhost:1234
spring.ai.openai.api-key=""
spring.ai.openai.embedding.options.model=text-embedding-nomic-embed-text-v1.5
spring.ai.openai.chat.options.model=ai/gemma3
spring.ai.openai.chat.base-url=http://localhost:12434/engines
spring.ai.openai.chat.api-key=ignored

# Spring AI Vector Configuration
spring.ai.vectorstore.pgvector.table-name=vector_store_iie_website_chatbot

#spring.ai.vectorstore.pgvector.index-type=HNSW
#spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
#spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.max-document-batch-size=10000
#spring.ai.vectorstore.pgvector.schema-validation=true
#spring.ai.vectorstore.pgvector.table-name=vector_store_pdf