spring.application.name=simple-spring-ai-rag=example


############### Comment these property if you need to load the file on start up ##
#app.vector.load-on-start-up=false
app.vector.pdf.file-path=C:\\Users\\Soham Sengupta\\Downloads\\bill bukku Feb 14 2025 netralaya.pdf

###################################################################################

######## JPA Configuration  #################
#### PostgreSQL Configuration ###
#############################################

spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb?options=-c%20TimeZone=Asia/Kolkata
spring.datasource.username=soham
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

##################################
# Spring AI OpenAI Configuration#
##################################

spring.ai.openai.base-url=http://localhost:1234
spring.ai.openai.api-key=""
spring.ai.openai.embedding.options.model=text-embedding-nomic-embed-text-v1.5
spring.ai.openai.chat.options.model=ai/gemma3
spring.ai.openai.chat.base-url=http://localhost:12434/engines
spring.ai.openai.chat.api-key=ignored
spring.ai.openai.chat.options.internalToolExecutionEnabled=true


#########################
##### Loggging Lecel ####
##########################



logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=DEBUG



